config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  #root "places#index"
  root "user#show"
  patch 'users/:id', to: 'user#update'
  resources :places
  resources :joins do
    collection do
      post :update_sanka
      patch :update_sanka
    end
  end
  resources :users
  resources :posts
  
  namespace :my do
    resources :events, only: [:index]
  end
end

app/models/place.rb
class Place < ApplicationRecord
    has_many :joins, dependent: :destroy
    has_many :users, through: :joins
    has_many :posts, dependent: :destroy

end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
    before_action :authenticate_user!

    def index
        @places = Place.all.order(etime: :DESC)
        @joins = Join.all
    end

    def show
        @place = Place.find(params[:id])
        @p_joins = Join.all.where("place_id = (?)", params[:id])
        @p_users = User.where("id IN (?)", @place.user_ids)
        @post = Post.new
        @posts = @place.posts.order(created_at: :DESC)
    end

    def new
        @place = Place.new
    end

    def create
        @place = Place.new(place_params)
        if @place.save
            redirect_to @place
        else
            render 'new'
        end
    end

    def edit
        @place = Place.find(params[:id])
    end

    def update
        @place = Place.find(params[:id])    
        if @place.update_attributes(place_params)
           redirect_to @place 
        else
            render 'edit'
        end
    end

    private
        def place_params
            params.require(:place).permit(:name, :menu, :intention_state , :stime, :etime)
        end

end

app/helpers/places_helper.rb
module PlacesHelper
end

app/views/places/edit.html.erb
<h1>場所修正</h1>

<div class="row">
    <%= form_for(@place) do |f| %>
        <%= f.label :name %>
        <%= f.text_field :name, class:'form-control' %>

        <%= f.label :menu %>
        <%= f.text_field :menu, class:'form-control' %>

        <div><label class="control-label">開始時間</label>
        <%= f.datetime_select :stime, class:'form-control' %></div>

        <div><label class="control-label">終了時間</label>
        <%= f.datetime_select :etime, class:'form-control' %></div>

        <%= f.submit "更新", class:"btn btn-primary" %>
    <% end %>
</div>

app/views/places/index.html.erb
<% @page_title = 'Syobo練一覧' %>
<div id="place-list">
<%= link_to "場所登録", new_place_path, class:"place-create btn btn-primary" %>

<div class="places">
    <% @places.each do |place| %>
    <% if place.etime >= DateTime.now %>
        <div class="place">
    <% else %>
        <div class="place finish">
    <% end %>
            <div class="title">
                <div class="name"><%= link_to place.name, place %></div>
                <div class="list">
                    <div><%= @joins.where("place_id = (?)", place.id).count %> 人</div>
                    絶対<%= place.joins.where("attend_flg = (?)", 0).count %>人
                    たぶん<%= place.joins.where("attend_flg = (?)", 1).count %>人
                    五分<%= place.joins.where("attend_flg = (?)", 2).count %>人
                    きびしいが<%= place.joins.where("attend_flg = (?)", 3).count %>人
                </div>
            </div>
            <div class="detail">
                <%= place.stime.strftime("%m/%d %a %H:%M〜") %><%= place.etime.strftime("%H:%M") %>
                <%= place.menu %>
            </div>
            <div class="btn-area">
                <div id="attend<%= place.id %>">
                    <%= render 'layouts/attend', place: place %>
                </div>
            </div>
        </div>
    <% end %>
</div>
</div>

app/views/places/new.html.erb
<h1>場所登録画面</h1>

<div class="row">
    <%= form_for(@place) do |f| %>
        <%= f.label :name %>
        <%= f.text_field :name, class:'form-control' %>

        <%= f.label :menu %>
        <%= f.text_field :menu, class:'form-control' %>

        <div><label class="control-label">開始時間</label>
        <%= f.datetime_select :stime, {
            use_month_numbers: true,
            discard_year: true,
            minute_step: 15,
            }, class:'sitme' %></div>

        <div><label class="control-label">終了時間</label>
        <%= f.datetime_select :etime, {
            use_month_numbers: true,
            discard_year: true,
            minute_step: 15,
            }, class:'eitme' %></div>

        <%= f.submit "登録", class:"btn btn-primary" %>
    <% end %>
</div>

app/views/places/show.html.erb
<% @page_title = @place.name %>
<div id="place-detail">
    <ul class="tab-group">
        <li class="tab is-active">詳細</li>
        <li class="tab">トーク</li>
        <li class="tab">地図</li>
    </ul>
    <div class="panel-group">
        <div class="panel is-show">
            <%= link_to "場所修正", edit_place_path, class:"btn btn-place-modify btn-primary"%>
    
            <div class="container">
                <div class="time"><%= @place.stime.strftime("%m/%d %a %H:%M〜") %><%= @place.etime.strftime("%H:%M") %></div>
                <div class="menu"><%= @place.menu %></div>
                <div class="list">
                    <div><%= @p_joins.count %> 人</div>
                    絶対<%= @p_joins.where("attend_flg = (?)", 0).count %>人
                    たぶん<%= @p_joins.where("attend_flg = (?)", 1).count %>人
                    五分<%= @p_joins.where("attend_flg = (?)", 2).count %>人
                    きびしいが<%= @p_joins.where("attend_flg = (?)", 3).count %>人
                </div>
                <div class="member">
                    <% @p_users.each do |user| %>
                        <div class="member-name">
                            <%= image_tag user.image.to_s %>
                            <%= user.name %>
                        </div>
                    <% end %>
                </div>
            </div>
        </div>
        <div class="panel">
            <%= render 'layouts/posts' %>
        </div>
        <div class="panel">
        </div>
    </div>
</div>