config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  #root "places#index"
  root "user#show"
  patch 'users/:id', to: 'user#update'
  resources :places
  resources :joins do
    collection do
      post :update_sanka
      patch :update_sanka
    end
  end
  resources :users
  resources :posts
  
  namespace :my do
    resources :events, only: [:index]
  end
end

app/views/layouts/_attend.html.erb
<%if current_user.joins.find_by(place_id: place.id).nil? %>
    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModalCenter<%= place.id %>">
        参加
    </button>
    <!-- モーダルの設定 -->
    <div class="modal fade" id="exampleModalCenter<%= place.id %>" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
      <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalCenterTitle">参加可能性を入力ください</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="閉じる">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
                    <%= form_for(current_user.joins.build) do |f| %>
                        <div><%= f.hidden_field :place_id, :value => place.id %></div>
                        <div><%= f.radio_button :attend_flg, 0 %> 絶対参加します</div>
                        <div><%= f.radio_button :attend_flg, 1 %> 多分参加します</div>
                        <div><%= f.radio_button :attend_flg, 2 %> 五分五分</div>
                        <div><%= f.radio_button :attend_flg, 3 %> きびしいけど行きたい</div>
                        <div class="modal-footer">
                            <%= f.submit "参加", class:"btn btn-primary" %>
                        </div>
                    <% end %>
          </div>
        </div>
      </div>
    </div>
<% else%>
    <%= form_for(current_user.joins.find_by(place_id: place.id),
                html: {method: :delete }, remote: true) do |f| %>
        <div><%= hidden_field_tag :place_id, place.id %></div>
        <%= f.submit "参加予定", class:"btn btn-primary btn-grayout" %>
    <% end %>
<% end %>

app/views/layouts/_header.html.erb
<header class="navbar navbar-inverse">
<div class="container">
<div class="logo"><%= link_to "しょぼ練", root_path %></div>
<nav>
    <ul class="nab navbar-nav navbar-right">
        <li><%= link_to "マイページ", root_path %></li>
        <li><%= link_to "しょぼれん探し", places_path %></li>
        <li><%= link_to "日記", "#" %></li>
    </ul>
</nav>
</div>
</header>

app/views/layouts/_posts.html.erb
        <%= form_for @post do |f| %>
        <%= f.hidden_field :user_id, :value => current_user.id %>
        <%= f.hidden_field :place_id, :value => @place.id %>
            <%= f.label "メッセージ" %>
            <%= f.text_field :content, class:"form-control" %>

            <%= f.submit "送信", class:"btn btn-primary" %>
        <% end %>
        <div class="line-bc">
            <% @posts.each do |post| %>
                <% if post.user_id != current_user.id %>
                    <div class="balloon6">
                        <div class="faceicon"><%= image_tag User.find(post.user_id).image.to_s %></div>
                        <div class="chatting">
                                <div class="name"><%= User.find(post.user_id).name %></div>
                            <div class="says">
                                <span><%= post.content %></span>
                            </div>
                            <span class="say-time"><%= post.created_at.strftime('%m/%d %H:%M') %></span>
                        </div>
                    </div>
                <% else %>
                    <div class="mycomment">
                        <span class="say-time"><%= post.created_at.strftime('%m/%d %H:%M') %></span>
                    <p>
                        <span><%= post.content %></span>
                    </p>
                    </div>
                <% end %>
            <% end %>
        </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= page_title_tag %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0,minimum-scale=1.0">
  </head>

  <body data-turbolinks="false">
    <%= render 'layouts/header' %>
    <div id="content">
      <% if current_user != nil %>
        <div id="header2">
          <span id="page-title"><%= @page_title %></span>
          <span id="user-name">
            <span><%= image_tag current_user.image.to_s %></span>
            <span>
              <%= current_user.name %>さん
              <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
              <%= link_to "ユーザー設定", edit_user_registration_path %>
            </span>
          </span>
        </div>
      <% else %>
      <% end %>

      <%= yield %>

      <div id="debug"><%= debug(params) if Rails.env.development? %></div>
    </div>
  </body>
</html>